export const planStubs = {
  todoList: [
    {
      id: '1',
      title: 'Review Testing resume',
      desc: 'this task is to review testing resume for an employee x',
      dueDate: '12/07/2020',
      status: 'OPEN',
      created_by: { name: 'Daniel', id: '123' },
      created_on: '12/01/2020',
      assigned_to: { name: 'Daniel', id: '123' },
      modified_on: '12/10/2020',
      sharedDoc_link:
        'https://docs.google.com/document/d/19wB6U6fxqU1UlXsVya7bHsJ1XY7gdgEKNrE4eXcGMRo/edit',
      tags: ['Review', 'Dev'],
      comments: [
        {
          comment: 'My First comment',
          created_by: { name: 'Daniel', id: '123' },
          created_on: '12/01/2020',
          attachments: [
            {
              id: '1',
              name: 'myDocument.docx',
              type: 'docx',
              url: '/path/to/doc/',
            },
            {
              id: '2',
              name: 'myDocument2.docx',
              type: 'docx',
              url: '/path/to/doc/',
            },
            {
              id: '3',
              name: 'myDocument3.docx',
              type: 'docx',
              url: '/path/to/doc/',
            },
          ],
        },
        {
          comment: 'My second comment',
          created_by: { name: 'John', id: '111' },
          created_on: '12/01/2020',
          attachments: [
            {
              id: '1',
              name: 'myDocument.pdf',
              type: 'pdf',
              url: '/path/to/doc/',
            },
          ],
        },
      ],
    },
    {
      id: '2',
      title: 'Review Dev resume',
      desc: 'this task is to review dev resume for an employee y',
      dueDate: '12/07/2020',
      status: 'OPEN',
      created_by: { name: 'Daniel', id: '123' },
      created_on: '12/01/2020',
      assigned_to: { name: 'Daniel', id: '123' },
      modified_on: '12/10/2020',
      sharedDoc_link:
        'https://docs.google.com/document/d/19wB6U6fxqU1UlXsVya7bHsJ1XY7gdgEKNrE4eXcGMRo/edit',
      tags: ['Review'],
      comments: [
        {
          comment: 'no comment',
          created_by: { name: 'Daniel', id: '123' },
          created_on: '12/01/2020',
        },
      ],
    },
  ],
  completedTab: [
    {
      id: '1',
      title: 'Grocery Pickup from Publix',
      desc: 'this task is to review testing resume for an employee x',
      dueDate: '12/07/2020',
      status: 'DONE',
      created_by: { name: 'Daniel', id: '123' },
      created_on: '12/01/2020',
      assigned_to: { name: 'Daniel', id: '123' },
      modified_on: '12/10/2020',
      sharedDoc_link:
        'https://docs.google.com/document/d/19wB6U6fxqU1UlXsVya7bHsJ1XY7gdgEKNrE4eXcGMRo/edit',
      comments: [
        {
          comment: 'test comment',
          created_by: { name: 'Daniel', id: '123' },
          created_on: '12/01/2020',
        },
      ],
    },
    {
      id: '2',
      title: "Create shopping list for Macy's",
      desc: 'this task is to review dev resume for an employee y',
      dueDate: '12/07/2020',
      status: 'DONE',
      created_by: { name: 'Daniel', id: '123' },
      created_on: '12/01/2020',
      assigned_to: { name: 'Daniel', id: '123' },
      modified_on: '12/10/2020',
      sharedDoc_link:
        'https://docs.google.com/document/d/19wB6U6fxqU1UlXsVya7bHsJ1XY7gdgEKNrE4eXcGMRo/edit',
      comments: [
        {
          comment: 'no comment',
          created_by: { name: 'Daniel', id: '123' },
          created_on: '12/01/2020',
        },
      ],
    },
  ],
  watchlistTab: [
    {
      id: '1',
      title: 'Create Plans list component',
      desc: 'this task is to review testing resume for an employee x',
      dueDate: '12/07/2020',
      status: 'OPEN',
      created_by: { name: 'Daniel', id: '123' },
      created_on: '12/01/2020',
      assigned_to: { name: 'Ben', id: '111' },
      modified_on: '12/10/2020',
      sharedDoc_link:
        'https://docs.google.com/document/d/19wB6U6fxqU1UlXsVya7bHsJ1XY7gdgEKNrE4eXcGMRo/edit',
      comments: [
        {
          comment: 'test comment',
          created_by: { name: 'Daniel', id: '123' },
          created_on: '12/01/2020',
        },
      ],
    },
    {
      id: '2',
      title: 'Review UI Changes for Plans',
      desc: 'this task is to review dev resume for an employee y',
      dueDate: '12/07/2020',
      status: 'IN_PROGRESS',
      created_by: { name: 'Daniel', id: '123' },
      created_on: '12/01/2020',
      assigned_to: { name: 'Vinoth', id: '222' },
      modified_on: '12/10/2020',
      sharedDoc_link:
        'https://docs.google.com/document/d/19wB6U6fxqU1UlXsVya7bHsJ1XY7gdgEKNrE4eXcGMRo/edit',
      comments: [
        {
          comment: 'no comment',
          created_by: { name: 'Daniel', id: '123' },
          created_on: '12/01/2020',
          attachments: [
            {
              id: '1',
              name: 'myDocument.docx',
              type: 'docx',
              url: '/path/to/doc/',
            },
          ],
        },
      ],
    },
  ],
  connections: [
    {
      userId: 51523,
      email: 'prashant.gupta@cardinaltsinc.net',
      firstName: 'Prashant',
      lastName: 'Gupta',
      qbid: '125075090',
      tillDate: false,
      connectionDate: '2021-02-06T13:08:28.106',
    },
    {
      userId: 51561,
      email: 'dharmarmepcoit@gmail.com',
      firstName: 'Dharmar',
      lastName: 'N',
      profileImageUrl: '/nonsecure/ua/profileImage/51561/image.jpg',
      qbid: '125075142',
      tillDate: false,
      connectionDate: '2021-01-12T17:18:50.382',
    },
    {
      userId: 51522,
      email: 'benneaser@gmail.com',
      firstName: 'Ben',
      lastName: 'John',
      profileImageUrl: '/nonsecure/ua/profileImage/51522/ben_john_headshot.jpg',
      designation: 'Working as a Chief Technology Officer',
      startDate: '01-06-2013',
      qbid: '125074055',
      tillDate: true,
      employerName: 'Xandr',
      connectionDate: '2020-12-23T18:41:17.636',
    },
  ],
  currentUser: {
    id: 51562,
    firstName: 'Daniel',
    lastName: 'Devadasan',
    emailId: 'dani.raja@gmail.com',
    mobileNumber: '',
    referedBy: 51522,
    source: 'NORMAL_SIGNUP',
    status: 'ACTIVE',
    nationality: 'undefined',
    dateOfBirth: '01-27-2021',
    gender: 'Male',
    qbid: 125075180,
    inviteCode: '927760',
    createdDate: '2020-12-23T18:33:11.785',
    registrationDate: '2020-12-23T18:41:17.622',
    isBasicDetail: false,
    isContactDetail: false,
    isEducationDetail: false,
    isExperienceDetail: false,
    isSkillDetail: false,
    isDeleteProfileImage: false,
    occupation: [
      {
        occupationId: 51557,
        occupationName: 'Engineer',
        occupationStatus: 'Developer',
        employerName: 'ADP',
        designation: '',
        tillDate: true,
        userId: 51562,
        startdate: '08-28-2015',
        endDate: null,
        createdDate: '2021-02-06T13:10:58.828',
      },
    ],
    role: [{ id: 51520, name: 'USER', privileges: null }],
  },
};
